import type { CatalogGame, CatalogResponse, Tag } from './types'

const tags: Tag[] = [
  { id: 'demo-chill', slug: 'chill', name: 'Chill' },
  { id: 'demo-thinky', slug: 'thinky', name: 'Thinky' },
  { id: 'demo-party', slug: 'party', name: 'Party' },
  { id: 'demo-cooperative', slug: 'cooperative', name: 'Cooperative' },
]

const baseGame: Omit<CatalogGame, 'id' | 'slug' | 'name'> = {
  itemType: 'game',
  containerId: 'demo-main-crate',
  containerSlug: 'main-crate',
  selectable: true,
  alwaysPacked: false,
  allowOverflow: true,
  widthMm: 300,
  heightMm: 75,
  depthMm: 300,
  weightGrams: null,
  minPlayers: 2,
  maxPlayers: 4,
  minPlayTimeMinutes: 30,
  maxPlayTimeMinutes: 60,
  complexity: 2,
  course: 'main',
  coverUrl: null,
  status: 'active',
  sortOrder: 0,
  tags: [tags[0], tags[1]],
}

const crateGames: CatalogGame[] = [
  { ...baseGame, id: 'demo-orchard', slug: 'demo-orchard', name: 'Orchard Atlas' },
  {
    ...baseGame,
    id: 'demo-moon-market',
    slug: 'demo-moon-market',
    name: 'Moon Market',
    widthMm: 285,
    heightMm: 65,
    depthMm: 285,
    minPlayers: 3,
    maxPlayers: 6,
    minPlayTimeMinutes: 60,
    maxPlayTimeMinutes: 100,
    complexity: 3,
    tags: [tags[1], tags[2]],
    sortOrder: 1,
  },
  {
    ...baseGame,
    id: 'demo-campfire',
    slug: 'demo-campfire',
    name: 'Campfire Stories',
    widthMm: 220,
    heightMm: 55,
    depthMm: 310,
    minPlayers: 2,
    maxPlayers: 5,
    minPlayTimeMinutes: 20,
    maxPlayTimeMinutes: 35,
    course: 'appetizer',
    complexity: 1,
    tags: [tags[0], tags[3]],
    sortOrder: 2,
  },
  {
    ...baseGame,
    id: 'demo-starlight',
    slug: 'demo-starlight',
    name: 'Starlight Bakers',
    widthMm: 250,
    heightMm: 70,
    depthMm: 250,
    minPlayers: 2,
    maxPlayers: 4,
    minPlayTimeMinutes: 75,
    maxPlayTimeMinutes: 130,
    course: 'dessert',
    complexity: 4,
    tags: [tags[1], tags[3]],
    sortOrder: 3,
  },
]

const toteGames: CatalogGame[] = [
  {
    ...baseGame,
    id: 'demo-pocket-parade',
    slug: 'demo-pocket-parade',
    name: 'Pocket Parade',
    containerId: 'demo-tote',
    containerSlug: 'board-game-tote',
    selectable: false,
    widthMm: null,
    heightMm: null,
    depthMm: null,
    minPlayTimeMinutes: 10,
    maxPlayTimeMinutes: 20,
    course: 'appetizer',
    tags: [tags[2]],
  },
  {
    ...baseGame,
    id: 'demo-tiny-truce',
    slug: 'demo-tiny-truce',
    name: 'Tiny Truce',
    containerId: 'demo-tote',
    containerSlug: 'board-game-tote',
    selectable: false,
    widthMm: null,
    heightMm: null,
    depthMm: null,
    minPlayTimeMinutes: 15,
    maxPlayTimeMinutes: 30,
    course: 'appetizer',
    tags: [tags[0], tags[3]],
  },
]

export const developmentCatalog: CatalogResponse = {
  containers: [
    {
      id: 'demo-main-crate',
      slug: 'main-crate',
      name: 'Main Crate',
      packingMode: 'bin_pack',
      selectionMode: 'individual',
      innerWidthMm: 600,
      innerHeightMm: 340,
      innerDepthMm: 400,
      overflowLimit: 2,
      isActive: true,
    },
    {
      id: 'demo-tote',
      slug: 'board-game-tote',
      name: 'Board Game Tote',
      packingMode: 'none',
      selectionMode: 'whole_container',
      innerWidthMm: null,
      innerHeightMm: null,
      innerDepthMm: null,
      overflowLimit: 0,
      isActive: true,
    },
  ],
  crateGames,
  toteGames,
  requiredCrateItems: [],
  tags,
}
